### ISSUE TITLE
Create Makefile for easier command executions

### ISSUE THREAD

**Issue by jeyren95** [jeyren95/big-bang-theory-quotes#4]
1. Build commands
2. Goose commands
-  create migration
-  goose up migration
-  goose down revert to previous migration

**Comment by k124k3n** [comment]
Issue already solved?

**Comment by jeyren95** [comment]
Nope, i can assign you this issue

**Comment by nesangcode** [comment]
No, just review my code. This is my first issue.

Edit: Oh thank you.

**Comment by nesangcode** [comment]
- For "create migration": 
Did it expect user to write the migration in text editor?

- For "goose up migration": 
Did it expect up-by-one or just up?

- For "goose down revert to previous migration":
Did it expect to add argument to _make_?
Example:
> make revert 1234567

**Comment by nesangcode** [comment]
I've made pull request. Please take a look on it.
